replicaCount: 2

image:
  repository: chetan6271/devops-app
  tag: 56c0b3db77c8ec61852b8a27a322baf9563d13fb
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
